//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManager.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ticket()
        {
            this.tickethistory = new HashSet<tickethistory>();
        }
    
        public int TicketId { get; set; }
        public int CustomerId { get; set; }
        public int ContactId { get; set; }
        public int CreateUserid { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> StatusDetailId { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string TicketIssueSubject { get; set; }
        public string TicketIssueDescription { get; set; }
        public Nullable<int> RespUserId { get; set; }
        public string OutlookEntryId { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual customer customer { get; set; }
        public virtual status status { get; set; }
        public virtual statusdetail statusdetail { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tickethistory> tickethistory { get; set; }
    }
}
