//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManager.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickethistory
    {
        public int TicketHistoryId { get; set; }
        public int TicketId { get; set; }
        public int TicketHistoryUserId { get; set; }
        public string TicketHistoryDetail { get; set; }
        public System.DateTime TicketHistoryDate { get; set; }

        public int StatusDetailId { get; set; }

        public virtual ticket ticket { get; set; }
        public virtual user user { get; set; }
        
        public virtual statusdetail statusdetail { get; set; }
    }
}
