//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TicketDBEntities : DbContext
{
    public TicketDBEntities()
        : base("name=TicketDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<contact> contact { get; set; }
    public virtual DbSet<customer> customer { get; set; }
    public virtual DbSet<status> status { get; set; }
    public virtual DbSet<statusdetail> statusdetail { get; set; }
    public virtual DbSet<ticket> ticket { get; set; }
    public virtual DbSet<tickethistory> tickethistory { get; set; }
    public virtual DbSet<user> user { get; set; }
}
